# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone_bill_call_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField(verbose_name='Call identifier')),
                ('source', models.CharField(max_length=11, verbose_name='Origin phone number')),
                ('destination', models.CharField(max_length=11, verbose_name='Destination phone number')),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('call_start', models.DateTimeField(verbose_name='call start date')),
                ('call_end', models.DateTimeField(verbose_name='call end date')),
                ('call_duration', models.TimeField(verbose_name='duration of the call')),
            ],
        ),
    ]
