# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_model',
            old_name='destination_phone_number',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='record_model',
            old_name='origin_phone_number',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='record_model',
            old_name='time',
            new_name='timestamp',
        ),
    ]
